### ISSUE TITLE
Subdirectories in _partials should be candidates for partial resolution

### ISSUE THREAD

**Issue by mhheise** [lynx-json/lynx-docs#109]
Suppose I have multiple related partials (say, a collection of partials related to input fields on a form) that could be logically grouped in a folder, and that collection of partials is shared among two or more root-level sibling functionalities such it is reasonable to place them in the `_partials` folder. I would like to be able to organize the partial collection as a subdirectory of `_partials`, like below:

```
├───foo
│   └───default.lynx.yml (implements `baz` partial and `spam`, `ham`, and `eggs` partials)
├───bar
│   └───default.lynx.yml (implements `spam`, `ham`, and `eggs` partials)
└───_partials
    ├───baz.yml
    └───inputs
        ├───eggs.yml
        ├───ham.yml
        └───spam.yml
```

**Comment by ansongoldade** [comment]
Resolved with PR #115
