### ISSUE TITLE
Tech Alignment: Qualified (Namespaced) Spec Properties.

### ISSUE THREAD

**Issue by johnhowes** [lynx-json/lynx-docs#31]
Currently, most partials use a wildcard syntax `spec.*` to create a placeholder for spec properties, but I'm this does not match qualified (namespaced) properties that must be referenced like this `spec["http://example.com/some-property"]`. The `spec.*` syntax should be understood to match both forms of property reference.

**Comment by ansongoldade** [comment]
Resolved with commit 26612ce7fa8528ef6662f269ac6745ba15984ea6.
