### ISSUE TITLE
Add "init" command to cli

### ISSUE THREAD

**Issue by ansongoldade** [lynx-json/lynx-docs#47]
I think it would be a nice to be able to issue a `lynx-docs init` command and have a small interview process, similar to `nmp init`, that initializes a directory for a lynx-docs application. 
- Create the folder that lynx templates go in. Default to lynx-templates or something like that.
- Create a default.lynx.yml file with default.data.yml file to show data binding. User can opt out of either or all.
- Create the .lynxdocsrc file using the value from first bullet. 
- Port to listen for requests
- Other stuff??

Thinking it might look something like this
```
lynx-docs init

This utility will walk you through creating a lynx-docs project. It only covers the most common items, and tries to guess sensible defaults.

template directory: (lynx-templates)
create default template: (yes)
create default data file: (yes)
create .lynxdocsrc run control: (yes)
port to listen for requests: (3000)

About to create the following items:
- lynx-templates folder
- deafult.lynx.yml template file
- default.data.yml data file
- .lynxdocsrc run control file with {root: ["./lynx-templates"], start: { port: 3000 } }

Is this okay? (yes)

Congratulations! Your lynx-docs project is initialized. Type "lynx-docs start" and open your browser to "http://localhost:3000/" to begin.
```
The result of those commands would be an initialized directory with a run control file, template directory with default documents, and a running server that is ready to handle requests. Maybe even include an index.html that references jsua and jsua-lynx so they can see a rendered document?

Maybe it's too early for this, but the thinking is to get somebody quickly to the first victory and let them build from that rather than forcing them to build the knowledge necessary to get to the first victory.

Let me know your thoughts.

**Comment by johnhowes** [comment]
I like it. What about “src” for templates directory, since that’s what we always do?

Also, I don't think you need to ask if we should create an rc file, since the other questions wouldn't have any result if they weren't captured in an rc file, right?

**Comment by ansongoldade** [comment]
I can see defaulting the templates to `src`. If the app is going to be a Nodejs app then they will probably have the templates in a different directory because their .js files will be in `src`. That's what Danny did.

Re: .lynxdocsrc. The default of `src` for the root would have an impact since the default if nothing is specified is `.`. The "port" question would also have an impact if they didn't accept the default. 

Maybe we should default root to `.` so that there is consistency between `init`, `start`, and `export`? Then we only need to create .lynxdocsrc if they don't use default values? I'm very open to suggestions about the best way to handle this.

**Comment by ansongoldade** [comment]
Going to close this issue since we haven't found it worth putting time into in the last 6 months. Don't think it's a high value ask and it's easy to recreate if it becomes valuable in the future.
