### ISSUE TITLE
Flattening Moves Dynamic Spec Out of Section

### ISSUE THREAD

**Issue by danmork** [lynx-json/lynx-docs#55]
The spec flattening process is moving a dynamic spec (a spec with spec properties that are bound to data parameter variables) out of a dynamic section that the spec's dynamic values are dependent upon for data binding context.

To recreate this issue, start lynx-docs with flattening enabled and navigate to the following template's default variant:

### template
```yaml
">list":
  spec.labeledBy: label
  "#firstName":
    label>: First Name
    firstName>line:
      value<value: ""
      spec.input: true
      spec.validation:
        required:
          state<requiredConstraintState: ""
          invalid: requiredError
    requiredError>text: Required
  "^firstName": null
```

### data
```yaml
firstName:
  value: ""
  requiredConstraintState: invalid
```

The expected result when navigating to this template is that the text input's required validation constraint will be in an `invalid` state. However, the actual result is that the text input's required validation constraint is in an `unknown` state.

The reason for the actual result is because the spec flattening process has moved the `spec` for the `firstName` property to the document level. At this level, there is no `requiredConstraintState` data variable for the required validation constraint's `state` property to bind to as that value is a child value of the `firstName` object value.

**Comment by ansongoldade** [comment]
I believe this issue was resolved with commit hash `024201271d0c081075f910b2ed0fbe344c4823e0` with an additional fix in commit hash `90ef7bd2e1b45d9af1763e7a9d7276ab014bca33`. If that is the case, then please close this issue.
