### ISSUE TITLE
Difference in Treatment of `realm` Value when Exporting Specs

### ISSUE THREAD

**Issue by johnhowes** [lynx-json/lynx-docs#62]
Consider the following YAML document:

```YAML
>lynx:
  realm: http://example.com/specified-realm/
  label>: Hello
```
When serving lynx-docs with the following command, the `realm` value is treated as a document-level property (it is not included in the `value`).

```
lynx-docs start --spec.dir "./src/main/webapp/specs/" --spec.url "/specs/" --spec.cache
```

This results in the following lynx document:

```JSON
{"realm":"http://example.com/specified-realm/","spec":"/specs/e421bfbffde8ad4d371c974c7348d933.lnxs","label":"Hello" }
```

When serving the same template without spec extraction, the `realm` property is included in the `value` and the default `realm` is used as the document realm, resulting in the following lynx document:

```JSON
{"realm":"http://bestbuy.com/retail/oms/hd/order/appointments-summary/calendar/","spec":{"hints":["container"],"children":[{"name":"label" }] },"value":{"realm":"http://example.com/specified-realm/","label":{"spec":{"hints":["label","text"] },"value":"Hello" } } }
```

When the template is modified by moving the `realm` property outside of the call to the `>lynx` partial, both commands correctly use the specified document realm.

My perspective is that the initial template was incorrectly providing a `realm` value property, and that it should not have been pulled up to the document level. In the interest of removing magic, we should expect the author to correctly provide a document-level `realm` property, but we should be consistent with this behavior, whether or not we're extracting specs.

**Comment by johnhowes** [comment]
To be clear, I think the template should have been authored as follows:

```YAML
realm: http://example.com/specified-realm/
>lynx:
  label>: Hello
```

**Comment by ansongoldade** [comment]
I believe what is happening is that when `spec` is defined, then `flatten` is inferred to be `true`. In the first example, when the template is flattened, the realm from the value component is over-writing the realm that was put at the root of the document. I agree that this is unexpected so should we just not flatten when the value/spec pair has a realm key and the value component has a realm key? This logic should probably apply to all document level properties if we do it.

**Comment by johnhowes** [comment]
It sounds like this will address the two problems of inconsistency and magic, so I think it basically makes sense. Thanks for the explanation.
